audit_header: false
title: "Nashville's Best Real Estate Training - Josh Anderson"
description: Josh Anderson, a top Real Estate Agent in Nashville, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: https://www.eventbrite.com/o/josh-anderson-17939924526
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/
  - title: Featured Podcasts
    url: /featured-podcasts/
client:
  name: Josh Anderson
  title:
  license_number:
  about_markdown: |
    At The Anderson Group, our agents specialize in building lasting relationships with our clients while helping them achieve their goal of finding a new home. Our team’s vast knowledge of Nashville’s ever-growing communities and commitment to client needs have helped us become one of the most trusted names in Nashville real estate.
  market: Nashville
  brand: The Anderson Group Real Estate Services
  brokerage: Keller Williams
  address: 2313 21st Avenue South<br>Nashville, TN 37212
  phone: 615-823-1555
  phone_type:
  phone2:
  phone2_type:
  email: Josh@JoshAndersonRealEstate.com
  url: https://JoshAndersonRealEstate.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how The Anderson Group Real Estate Services can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/NashvilleTennesseeRealEstate/
  linkedin_url: https://www.linkedin.com/company/the-anderson-group-real-estate
  youtube_url: https://www.youtube.com/channel/UCfIQVJWx55GuxgSJTeFLi5A
  twitter_url: https://twitter.com/AndersonGroupRE
  instagram_url: https://www.instagram.com/tagrealestate/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://podcasts.apple.com/us/podcast/episode-07-master-the-basics-with-josh-anderson/id1475264745?i=1000449272453

podcast:
  title: 'Nashville Real Estate Podcast with Josh Anderson'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Nashville Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Anderson Group Real Estate Services - your professional Nashville Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Nashville, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Josh Anderson'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Nashville Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background2.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#f09854'
  theme_color: '#3b3042'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#f09854'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
